### ISSUE TITLE
I attempted to log in and navigated to the My Info page. There was nothing on the page.

### ISSUE THREAD

**Issue by xNatthapol** [WordWiseProject/WordWise#40]
<img width="1440" alt="image" src="https://github.com/WordWiseProject/WordWise/assets/115071646/2d1ac9a3-b2f4-4034-b61b-abef8f604cbd">

**Comment by 21Gxme** [comment]
It just a placeholder. We will delete it on next iteration.

**Comment by jbrucker** [comment]
If there was a link to this page in your deployed application,
and the user can nagivate to an empty page (expecting a "My Info" page),
then this is a defect.

There should not be links to unimplemented features in the deployed app.

**Comment by 21Gxme** [comment]
Thank you [jbrucker](https://github.com/jbrucker) for your suggestion
