### ISSUE TITLE
The content is too long, causing the content to overflow the box.

### ISSUE THREAD

**Issue by SmileyFaceZ** [WordWiseProject/WordWise#42]
<img width="1439" alt="Screenshot 2566-11-23 at 00 11 19" src="https://github.com/WordWiseProject/WordWise/assets/113492355/6fd140fb-f3f3-4662-b057-691c110aacbf">

**Comment by 21Gxme** [comment]
fix in 69899c10c574ff438b2e7cb6b56af50d2652aa2e. Thank you for report.
