### ISSUE TITLE
I got a random username

### ISSUE THREAD

**Issue by Jwizzed** [WordWiseProject/WordWise#44]
I logged in using google OAuth with the email krittin.set@ku.th but I somehow got the username krittin7.
<img width="514" alt="Screenshot 2566-11-23 at 22 50 48" src="https://github.com/WordWiseProject/WordWise/assets/101621268/8c53c487-7ae6-4311-a254-f0c6c079e52f">

**Comment by 21Gxme** [comment]
Google Oauth handle it when it have duplicate name
