### ISSUE TITLE
Can login and signup without Google Account (Using Allauth route)

### ISSUE THREAD

**Issue by Sosokker** [WordWiseProject/WordWise#46]
It look like we can still navigating to [https://wordwise-project-c6b7ee2f234f.herokuapp.com/accounts/signup](https://wordwise-project-c6b7ee2f234f.herokuapp.com/accounts/signup) and to [https://wordwise-project-c6b7ee2f234f.herokuapp.com/accounts/login](https://wordwise-project-c6b7ee2f234f.herokuapp.com/accounts/login) too.

I'm not sure is this one of the feature that user can choose to login or not.

**Comment by 21Gxme** [comment]
I apologize for accidentally marking Not a Defect as my mistake. We will fix it later Thank you for your reporting.
