### ISSUE TITLE
div is disappear at authentication.

### ISSUE THREAD

**Issue by Jwizzed** [WordWiseProject/WordWise#48]
When I log in 2 tabs with a different account. The log out div is disappear.
<img width="613" alt="Screenshot 2566-11-24 at 21 55 10" src="https://github.com/WordWiseProject/WordWise/assets/101621268/244a17d7-b061-4efd-b581-6bede3793433">

**Comment by ReggieReo** [comment]
fixed in 320524f908e6f26d2c973c4e2794498ca5ff9189 will deploy later.
