### ISSUE TITLE
Locking deck is not working

### ISSUE THREAD

**Issue by J-Jullaphong** [WordWiseProject/WordWise#50]
I tried locking my deck (jongmaihub deck), but when I am not logged in, I can still access (use flash card, fill in the blank, and also test mode). Maybe I misunderstood the purpose of your deck locking feature.

### This is when I logged in with JongMaiHUB account.
<img width="1512" alt="Screenshot 2566-11-25 at 21 49 10" src="https://github.com/WordWiseProject/WordWise/assets/111471511/bbd7f682-23bf-427f-8b53-6847aaa8dc1a">

### This is when I logged out.
<img width="1512" alt="Screenshot 2566-11-25 at 21 49 39" src="https://github.com/WordWiseProject/WordWise/assets/111471511/3f0e3478-0b39-4d26-a2cc-6fc7067e3e1a">

**Comment by 21Gxme** [comment]
Now it just a mock-up. Work in progress. Thank you for reporting.
