### ISSUE TITLE
Incorrect profile information

### ISSUE THREAD

**Issue by J-Jullaphong** [WordWiseProject/WordWise#51]
Seems like the statistics for each user in the profile page are the same for every user. Not sure if this is just a mock-up?

### JongMaiHUB account
<img width="1512" alt="Screenshot 2566-11-25 at 22 02 04" src="https://github.com/WordWiseProject/WordWise/assets/111471511/2a9f7fda-c84a-493f-9789-85f99cea83b1">

### My own account
<img width="1512" alt="Screenshot 2566-11-25 at 22 03 36" src="https://github.com/WordWiseProject/WordWise/assets/111471511/764970fa-06e7-4b03-b8fa-c9fddf374770">

**Comment by 21Gxme** [comment]
Now it just a mock-up. Work in progress. Thank you for reporting.

**Comment by 21Gxme** [comment]
I implement it already
